version: '3'

services:

        article-db:
                image: postgres
                restart: always
                environment:
                        POSTGRES_PASSWORD: qwerty
                ports:
                       - 5432:5432
